---
all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519

  children:
    proxmox:
      hosts:
        proxmox-01:
          ansible_host: 192.168.1.37

    monitoring_vms:
      hosts:
        monitoring-01:
          ansible_host: 192.168.1.50
          ansible_user: ubuntu

    pbs_vms:
      hosts:
        pbs-01:
          ansible_host: 192.168.1.51
          ansible_user: debian

    gitea_vms:
      hosts:
        gitea-01:
          ansible_host: 192.168.1.52
          ansible_user: ubuntu
