apiVersion: 1
contactPoints:
  - orgId: 1
    name: email-alerts
    receivers:
      - uid: email-receiver
        type: email
        settings:
          addresses: ${GF_SMTP_USER}
          singleEmail: false
        disableResolveMessage: false
